### PR TITLE
Deduplication of Solr Documents

### LINKED ISSUE #71: *_md fields generated by parser are not present in the Solr schema
The Tika extractions are converted into `*_type_md` format but doesn't account for `*_md`. We have one such case below. Suggested actions:

- Look for the root cause and fix it.
- Catch these exceptions so that the crawl don't break.

**Exception**

```
17/01/31 03:50:07 WARN scheduler.TaskSetManager: Lost task 106.3 in stage 36.0 (TID 3379, xxxxxx): org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error 
from server at http://xxxxx:8983/solr/crawldb: ERROR: [doc=01032A21DC592B721AC96AF6F71E08AB5587791C0476F9A3E2156FD0F882898A] unknown field 'id_md'
	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:577)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:241)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:230)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:149)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:209)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:224)
	at edu.usc.irds.sparkler.service.SolrProxy.addResourceDocs(SolrProxy.scala:35)
	at edu.usc.irds.sparkler.solr.SolrStatusUpdate.apply(SolrStatusUpdate.scala:37)
	at edu.usc.irds.sparkler.solr.SolrStatusUpdate.apply(SolrStatusUpdate.scala:32)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by karanjeets**
Closes #71 and #72 

Solr doesn't provide the Upsert methodology out of the box. Created another field `dedupe_id` field in Solr which stores the `SHA256(crawl_id-url)`.

Also, commented `overrides: id` from solr-schema-map.yaml to include `id` in the field formatting for Solr. Please note that this `id` field is from Tika metadata.

### CODE REVIEW

**Comment by karanjeets** [comment]
@thammegowda Please review.

File: sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala [hunk 1]
```diff
@@ -38,9 +37,16 @@ class SolrUpsert(job: SparklerJob) extends ((TaskContext, Iterator[Resource]) =>
     val solrClient = job.newCrawlDbSolrClient()
 
     //TODO: handle this in server side - tell solr to skip docs if they already exist
-    val newResources: Iterator[Resource] = for (doc <- docs if solrClient.crawlDb.getById(doc.getId) == null) yield doc
+    var newResources: Set[Resource] = Set()
```
Comment (thammegowda) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: I am gonna restore lazy evaluations here.

FYI, the catch here is when we convert `Iterator[Resource]` to `Set[resource]` lazy evaluations are gone and thus we are starting to buffer, eventually it may overflow in some settings!

File: sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala [hunk 2]
```diff
@@ -38,9 +37,16 @@ class SolrUpsert(job: SparklerJob) extends ((TaskContext, Iterator[Resource]) =>
...
+    for (doc <- docs) {
+      val qry: SolrQuery = new SolrQuery(Constants.solr.STATUS + ":" + ResourceStatus.UNFETCHED)
+      qry.addFilterQuery(s"${Constants.solr.DEDUPE_ID}:${doc.getDedupeId}")
```
Comment (thammegowda) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: @karanjeets 
So, this query looks for `status:UNFETCHED AND dedub_id:<dedupe_id>`

My question is why `status:UNFETCHED`  filter required? Do you mean to overwrite already fetched?

Is it a bug or am I missing something?

File: sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala (hunk 1 above)
Comment (karanjeets) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: @thammegowda 
That's wise! We should have `Iterator[Resource]`

File: sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala (hunk 2 above)
Comment (karanjeets) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: This is a bug. I was trying to query only the `FETCHED` documents but firstly I forgot `!` and secondly I understand that this will not work. We have to look up all the documents. This should be changed to `*:*`

Comment (thammegowda) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: isn't the query as simple as `dedupe_id:<dedupe_id>` to count number of hits?
What am I missing with this query?

Comment (karanjeets) [inline sparkler-app/src/main/scala/edu/usc/irds/sparkler/solr/SolrUpsert.scala]: Yes, that's also correct.

**Comment by thammegowda** [comment]
👍  Thanks @karanjeets
